## CS559: Homework #1

Assignment #1: due on **2/23/2021 by 11:59 PM**. 
- Change the file name as *YourName*_S21_CS559_HW1
- Submit the assignment both in format of *ipynb* and *html*. 
    - You can export the file as *html* as `File`>`Download as`>`HTML`. The assignment should be own work and must not be shared between classmates. 
- You **do not need to compress** the files. You can submit individual files.
- This assignment focuses on two topics - linear algebra and data pre-processing. 
    - For linear algebra questions, when the question says "implement", you cannot use any built-in functions.
- This assignment should an individual work. Do not collaborate with classmates or get help from 3rd person. You may surf internet if you need to. Then site the reference. 

### Problem 1 [10 pts]
- Implement a function `dot_product` to calculate the dot product of two 1 by n arrays. [6 pts] 
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [1]:
import numpy as np
import math
import pandas as pd


In [2]:
### Code Starts Here
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])
def dot_product(a, b):
    #iter through a and b
    ans = 0
    for i in range(0,a.size):
        times= a[i] *b[i]
        ans +=times 
    return ans
        

        

In [3]:
dot_product(a,b)
a.shape

(4,)

- Test your code after generating two random 1 by 10 arrays. [4 pts]

In [4]:
### Code Starts Here
c = np.random.random((10,))
d = np.random.random((10,))
dot_product(c,d)

3.2439030943697893

### Problem 2 [10 pts]
- Consider three vectors ${\bf x}_1=(1,3), {\bf x}_2=(-1,5)$, and ${\bf x}_3=(0,7)$. Find the distance of each point from the **origin**. [4 pts]

In [5]:
### Code Starts Here
x1= np.array([1,3])
x2= np.array([-1,5])
x3=np.array([0,7])

def vectorDistance(x):
    #take the sqaureroot of the elements squared
    squaredSum = x[0]**2+x[1]**2
    root = math.sqrt(squaredSum)
    return root
    

In [6]:
vectorDistance(x1), vectorDistance(x2), vectorDistance(x3)

(3.1622776601683795, 5.0990195135927845, 7.0)

- Rotate the coordinates by 35 degress in counter clockwise. [4 pts]

In [7]:
### Code Starts Here
#x new = cosBx1-sinBy1
#ynew = sinBx1+cosBy1
def vectorRotate(x, deg):
    #note math.cos and math.sine work in rads!
    #convert degrees to radianns
    rads = deg*0.01745329
    xnew = (math.cos(rads)*x[0])-(math.sin(rads)*x[1])
    ynew = (math.sin(rads)*x[0])+(math.cos(rads)*x[1])
    newVec = np.array([xnew, ynew])
    return newVec

In [8]:
vectorRotate(x1,35)

array([-0.901577  ,  3.03103265])

In [9]:
vectorRotate(x2,35)

array([-3.68703392,  3.52218411])

In [10]:
vectorRotate(x3,35)

array([-4.01503455,  5.73406466])

- Magnify the area by 4 times. [2 pts]

In [11]:
### Code Starts Here
#multiply vectors x1 x2 x3 by 4
x1 = x1 *4
x2 = x2*4
x3 = x3*4
x1, x2, x3

(array([ 4, 12]), array([-4, 20]), array([ 0, 28]))

### Problem 3 [20 pts]
- Implement a function `mat_product` to calculate the matrix product of two n by n arrays. [8 pts] For example:


$A = \begin{bmatrix} 1 & 3 & 0 \\ 2 & 0 & 2 \\ 1 & 1 & 4 \end{bmatrix}$ and $A\cdot A=\begin{bmatrix} 7 & 3 & 6 \\ 4 & 8 & 8 \\ 7 & 8 & 18 \end{bmatrix}$

    mat_product(A,A)=?

In [12]:
### Code Starts Here
a1= np.array([1, 3, 0])
a2 = np.array([2,0,2])
a3 = np.array([1,1,4])
A = np.vstack([a1, a2, a3])


    

In [13]:
A, A.shape

(array([[1, 3, 0],
        [2, 0, 2],
        [1, 1, 4]]), (3, 3))

In [14]:
A[1:2,:]

array([[2, 0, 2]])

In [15]:
def mat_product(A,B):
    #first check that the matricies are in form mxn nxp = mxp
    if A.shape[1] != B.shape[0]:
        return "The Number of columns in A must equal the number of rows in B"
    else:
        # C = mxp
        C = np.zeros((A.shape[0],B.shape[1]))
        #iter through rows first 
        for i in range(0,C.shape[0]):
            for j in range(0,C.shape[1]):
                C[i,j] = dot_product(A[i:i+1,:].T,B[:,j:j+1])
        return C
            
        
    

In [16]:
C = mat_product(A,A)
C

array([[ 7.,  3.,  6.],
       [ 4.,  8.,  8.],
       [ 7.,  7., 18.]])

- Test your code after generating two random 4 by 4 matrices, ${\bf X}$ and ${\bf Y}$. [4 pts]

In [17]:
### Test Starts Here
X = np.random.random((4,4))
Y = np.random.random((4,4))
mat_product(X,Y)

array([[0.78608887, 0.92820833, 1.03409442, 0.85882181],
       [1.5719413 , 1.52363874, 1.37718555, 1.3664686 ],
       [1.14998471, 1.14058761, 0.97395796, 0.98481678],
       [0.78904752, 1.0257013 , 0.67484895, 0.6348927 ]])

- Inplement a function `mat_transpose` that transposes ${\bf X}$ and use the `mat_product` function to find the matrice of product: $Z={\bf X}^T\cdot{\bf Y}$ [8 pts]

        Z=mat_product(mat_transpose(X),Y)

In [18]:
### Code Starts Here
def mat_transpose(x):
    #we want to swap the rows and columns
    transpose = np.zeros((x.shape[1],x.shape[0]))
    for i in range(0,x.shape[0]):
        for j in range(0,x.shape[1]):
            transpose[j,i] = x[i,j]
    return transpose
    

In [19]:
A

array([[1, 3, 0],
       [2, 0, 2],
       [1, 1, 4]])

In [20]:
A_T = mat_transpose(A)
A_T

array([[1., 2., 1.],
       [3., 0., 1.],
       [0., 2., 4.]])

### Problem 4 [30 pts]
- In this question, we will use the csv file **Temp.csv**. This question task is a process of exploratory data ansysis (EDA) to learn about data itself. Read it into a data frame, call it `Temp`. (Import the packages you think you need). [4 pts]

In [21]:
### Code Starts Here
Temp = pd.read_csv("Temp.csv")
Temp

City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68

- We learned that the temperature at New Haven, Connecticut is currently 58 degree fahrenheit. Add this information into the DataFrame.[4 pts]

In [22]:
### Code Starts Here
newHaven = ["New Haven", "Connecticut", 58]
Temp.loc[7] = newHaven
Temp

City        State  Temperature
0         NYC     New York           67
1      Albany     New York           49
2     Buffalo     New York           38
3    Hartford  Connecticut           63
4  Bridgeport  Connecticut           58
5      Treton   New Jersey           72
6      Newark   New Jersey           68
7   New Haven  Connecticut           58

- Replace the names of the states by their abbreviations. [4 pts] That is 
    - Connecticut --> CT
    - New Jersey  --> NJ
    - New York    --> NY

In [23]:
### Code Starts Here

Temp['State'].replace('New York', 'NY',inplace=True)
Temp['State'].replace('Connecticut', 'CT',inplace=True)
Temp['State'].replace('New Jersey', 'NJ', inplace=True)
Temp

City State  Temperature
0         NYC    NY           67
1      Albany    NY           49
2     Buffalo    NY           38
3    Hartford    CT           63
4  Bridgeport    CT           58
5      Treton    NJ           72
6      Newark    NJ           68
7   New Haven    CT           58

- Select the rows in New York. [2 pts]

In [24]:
### Code Starts Here
state = Temp.groupby(['State'])
state.get_group('NY')

City State  Temperature
0      NYC    NY           67
1   Albany    NY           49
2  Buffalo    NY           38

- What is the average of the temperature of cities in NY? [4 pts]

In [25]:
### Code Starts Here
state.get_group("NY")['Temperature'].agg(np.mean)

51.333333333333336

- Find the mean and the standard deviation of the temperature of each state. [4 pts]

In [26]:
### Code Starts Here

tempStats = state['Temperature'].agg([np.mean, np.std])
tempStats


mean        std
State                      
CT     59.666667   2.886751
NJ     70.000000   2.828427
NY     51.333333  14.640128

- Create a data frame `Capital`, with two columns: State and Capital. [4 pts] 

    We know the capital of each state: 
    - Connecticut --> Hartford
    - New Jersey  --> Treton
    - New York    --> Albany
    
|| State| Capital|
| :-: |:---: | :---:|
| 0| CT  | Hartford|
| 1| NJ | Treton|
| 2| NY| Albany|

In [27]:
### Code Starts Here
Capital = pd.DataFrame(columns =["State", "Capital"])
CT = ["CT", "Hartford"]
Capital.loc[0] = CT
NJ= ["NJ", "Treton"]
Capital.loc[1] = NJ
NY = ["NY", "Albany"]
Capital.loc[2]= NY
Capital

State   Capital
0    CT  Hartford
1    NJ    Treton
2    NY    Albany

- Mutate a new boolean column, `Capital`, to `Temp`, which is `True` if the city in the row is the capital of the state, else `False`. [4 pts]

In [28]:
### Code Starts Here
Temp['Capital'] = Temp['City'].isin(Capital['Capital'])
Temp

City State  Temperature  Capital
0         NYC    NY           67    False
1      Albany    NY           49     True
2     Buffalo    NY           38    False
3    Hartford    CT           63     True
4  Bridgeport    CT           58    False
5      Treton    NJ           72     True
6      Newark    NJ           68    False
7   New Haven    CT           58    False

### Problem 5 [30 pts]

- a. Load the Gross Domestic Product data for the 190 ranked countries in the file **GDP.csv**. Load **Country.csv** into a DataFrame. [6 pts]

In [29]:
### Code Starts Here
gdp = pd.read_csv("GDP.csv",encoding = "ISO-8859-1")
country = pd.read_csv("Country.csv",encoding = "ISO-8859-1")

In [30]:
gdp

Unnamed: 0 Gross domestic product 2012  Unnamed: 2     Unnamed: 3  \
0          NaN                         NaN         NaN            NaN   
1          NaN                         NaN         NaN            NaN   
2          NaN                     Ranking         NaN        Economy   
3          NaN                         NaN         NaN            NaN   
4          USA                           1         NaN  United States   
..         ...                         ...         ...            ...   
325        NaN                         NaN         NaN            NaN   
326        NaN                         NaN         NaN            NaN   
327        NaN                         NaN         NaN            NaN   
328        NaN                         NaN         NaN            NaN   
329        NaN                         NaN         NaN            NaN   

       Unnamed: 4 Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  
0             NaN        NaN         NaN         NaN         NaN         NaN  
1    (millions of        NaN         NaN         NaN         NaN         NaN  
2     US dollars)        NaN         NaN         NaN         NaN         NaN  
3             NaN        NaN         NaN         NaN         NaN         NaN  
4     16,244,600         NaN         NaN         NaN         NaN         NaN  
..            ...        ...         ...         ...         ...         ...  
325           NaN        NaN         NaN         NaN         NaN         NaN  
326           NaN        NaN         NaN         NaN         NaN         NaN  
327           NaN        NaN         NaN         NaN         NaN         NaN  
328           NaN        NaN         NaN         NaN         NaN         NaN  
329           NaN        NaN         NaN         NaN         NaN         NaN  

[330 rows x 10 columns]

In [31]:
#Find number of NAN values in each column
gdp.isna().sum()

Unnamed: 0                     102
Gross domestic product 2012    135
Unnamed: 2                     330
Unnamed: 3                     101
Unnamed: 4                     101
Unnamed: 5                     324
Unnamed: 6                     330
Unnamed: 7                     330
Unnamed: 8                     330
Unnamed: 9                     330
dtype: int64

In [32]:
#coulmns 2, 6, 7, 8, 9 are all empty
gdp = gdp.drop(['Unnamed: 2','Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'], axis=1)

In [33]:
#check values in Unnamed: 5
gdp['Unnamed: 5'].unique()
#data does not seem to be useful

array([nan, 'a', 'b', 'c', 'd', 'e', 'f'], dtype=object)

In [34]:
#remove Unnamed: 5
gdp =gdp.drop(['Unnamed: 5'], axis=1)

In [35]:
#Drop NAN values
gdp = gdp.dropna(how='all')

In [36]:
#Rename columns
gdp = gdp.rename(columns = {'Unnamed: 0':'CountryCode','Gross domestic product 2012':'Ranking', 'Unnamed: 3':'Economy','Unnamed: 4': 'Millions of US Dollars'})

In [37]:
#Remove entries without ranking
gdp = gdp[gdp['Ranking'].notna()]
gdp

CountryCode                                            Ranking  \
2           NaN                                            Ranking   
4           USA                                                  1   
5           CHN                                                  2   
6           JPN                                                  3   
7           DEU                                                  4   
..          ...                                                ...   
193         TUV                                                190   
236         NaN                                .. Not available.     
237         NaN  Note: Rankings include only those economies wi...   
238         NaN  a. Includes Former Spanish Sahara.  b. Exclude...   
239         NaN  controlled by the government of the Republic o...   

           Economy Millions of US Dollars  
2          Economy            US dollars)  
4    United States            16,244,600   
5            China             8,227,103   
6            Japan             5,959,718   
7          Germany             3,428,131   
..             ...                    ...  
193         Tuvalu                    40   
236            NaN                    NaN  
237            NaN                    NaN  
238            NaN                    NaN  
239            NaN                    NaN  

[195 rows x 4 columns]

In [38]:
#remove entries without countryCode
gdp = gdp[gdp["CountryCode"].notna()]
gdp

CountryCode Ranking                Economy Millions of US Dollars
4           USA       1          United States            16,244,600 
5           CHN       2                  China             8,227,103 
6           JPN       3                  Japan             5,959,718 
7           DEU       4                Germany             3,428,131 
8           FRA       5                 France             2,612,878 
..          ...     ...                    ...                    ...
189         STP     186  São Tomé and Principe                   263 
190         PLW     187                  Palau                   228 
191         MHL     188       Marshall Islands                   182 
192         KIR     189               Kiribati                   175 
193         TUV     190                 Tuvalu                    40 

[190 rows x 4 columns]

In [39]:
gdp

CountryCode Ranking                Economy Millions of US Dollars
4           USA       1          United States            16,244,600 
5           CHN       2                  China             8,227,103 
6           JPN       3                  Japan             5,959,718 
7           DEU       4                Germany             3,428,131 
8           FRA       5                 France             2,612,878 
..          ...     ...                    ...                    ...
189         STP     186  São Tomé and Principe                   263 
190         PLW     187                  Palau                   228 
191         MHL     188       Marshall Islands                   182 
192         KIR     189               Kiribati                   175 
193         TUV     190                 Tuvalu                    40 

[190 rows x 4 columns]

In [42]:
country

CountryCode                         Long Name          Income Group  \
0           ABW                             Aruba  High income: nonOECD   
1           ADO           Principality of Andorra  High income: nonOECD   
2           AFG      Islamic State of Afghanistan            Low income   
3           AGO       People's Republic of Angola   Lower middle income   
4           ALB               Republic of Albania   Upper middle income   
..          ...                               ...                   ...   
229         YEM                 Republic of Yemen   Lower middle income   
230         ZAF          Republic of South Africa   Upper middle income   
231         ZAR  Democratic Republic of the Congo            Low income   
232         ZMB                Republic of Zambia            Low income   
233         ZWE              Republic of Zimbabwe            Low income   

                         Region Lending category Other groups  \
0     Latin America & Caribbean              NaN          NaN   
1         Europe & Central Asia              NaN          NaN   
2                    South Asia              IDA         HIPC   
3            Sub-Saharan Africa              IDA          NaN   
4         Europe & Central Asia             IBRD          NaN   
..                          ...              ...          ...   
229  Middle East & North Africa              IDA          NaN   
230          Sub-Saharan Africa             IBRD          NaN   
231          Sub-Saharan Africa              IDA         HIPC   
232          Sub-Saharan Africa              IDA         HIPC   
233          Sub-Saharan Africa            Blend          NaN   

          Currency Unit Latest population census   Latest household survey  \
0         Aruban florin                     2000                       NaN   
1                  Euro           Register based                       NaN   
2        Afghan afghani                     1979                MICS, 2003   
3        Angolan kwanza                     1970  MICS, 2001, MIS, 2006/07   
4          Albanian lek                     2001                MICS, 2005   
..                  ...                      ...                       ...   
229         Yemeni rial                     2004                MICS, 2006   
230  South African rand                     2001                 DHS, 2003   
231     Congolese franc                     1984                  DHS 2007   
232      Zambian kwacha                     2000                 DHS, 2007   
233     Zimbabwe dollar                     2002              DHS, 2005/06   

                                         Special Notes  ...  \
0                                                  NaN  ...   
1                                                  NaN  ...   
2    Fiscal year end: March 20; reporting period fo...  ...   
3                                                  NaN  ...   
4                                                  NaN  ...   
..                                                 ...  ...   
229                                                NaN  ...   
230  Fiscal year end: March 31; reporting period fo...  ...   
231                                                NaN  ...   
232                                                NaN  ...   
233  Fiscal year end: June 30; reporting period for...  ...   

    Source of most recent Income and expenditure data  \
0                                                 NaN   
1                                                 NaN   
2                                                 NaN   
3                                           IHS, 2000   
4                                          LSMS, 2005   
..                                                ...   
229                                       ES/BS, 2005   
230                                       ES/BS, 2000   
231                                    1-2-3, 2005-06   
232                                      IHS, 2004-05   
2

- b. Match the data based on the country shortcode. How many of the IDs match? [6 pts]

In [43]:
### Code Starts Here
#match data by merging two dataframes

df3= pd.merge(gdp,country,how = 'inner',left_on='CountryCode', right_on='CountryCode')
df3

CountryCode Ranking                Economy Millions of US Dollars  \
0           USA       1          United States            16,244,600    
1           CHN       2                  China             8,227,103    
2           JPN       3                  Japan             5,959,718    
3           DEU       4                Germany             3,428,131    
4           FRA       5                 France             2,612,878    
..          ...     ...                    ...                    ...   
184         STP     186  São Tomé and Principe                   263    
185         PLW     187                  Palau                   228    
186         MHL     188       Marshall Islands                   182    
187         KIR     189               Kiribati                   175    
188         TUV     190                 Tuvalu                    40    

                                        Long Name         Income Group  \
0                        United States of America    High income: OECD   
1                      People's Republic of China  Lower middle income   
2                                           Japan    High income: OECD   
3                     Federal Republic of Germany    High income: OECD   
4                                 French Republic    High income: OECD   
..                                            ...                  ...   
184  Democratic Republic of São Tomé and Principe  Lower middle income   
185                             Republic of Palau  Upper middle income   
186              Republic of the Marshall Islands  Lower middle income   
187                          Republic of Kiribati  Lower middle income   
188                                        Tuvalu  Lower middle income   

                    Region Lending category Other groups  \
0            North America              NaN          NaN   
1      East Asia & Pacific             IBRD          NaN   
2      East Asia & Pacific              NaN          NaN   
3    Europe & Central Asia              NaN    Euro area   
4    Europe & Central Asia              NaN    Euro area   
..                     ...              ...          ...   
184     Sub-Saharan Africa              IDA         HIPC   
185    East Asia & Pacific             IBRD          NaN   
186    East Asia & Pacific             IBRD          NaN   
187    East Asia & Pacific              IDA          NaN   
188    East Asia & Pacific              NaN          NaN   

                   Currency Unit  ...  \
0                    U.S. dollar  ...   
1                   Chinese yuan  ...   
2                   Japanese yen  ...   
3                           Euro  ...   
4                           Euro  ...   
..                           ...  ...   
184  São Tomé and Principe dobra  ...   
185                  U.S. dollar  ...   
186                  U.S. dollar  ...   
187            Australian dollar  ...   
188            Australian dollar  ...   

    Source of most recent Income and expenditure data  \
0                                            LFS 2000   
1                                           IHS, 2005   
2                                            IS, 1993   
3                                           IHS, 2000   
4                                      ES/BS, 1994/95   
..                                                ...   
184                                        PS 2000-01   
185                                               NaN   
186                                               NaN   
187                                               NaN   
188                                               NaN   

    Vital registration complete Latest agricultural census  \
0                           Yes                  1997/2002   
1                           NaN                       1997   
2                           Yes                       2000   
3                           Yes                  1999-2000   
4                           Y

- c. Sort the data frame in descending order by GDP rank. What is the 13th country in the resulting data frame? (Note: GDP formats as 123,456,789.) [6 pts]

In [44]:
### Code Starts Here
df3 = df3.sort_values(by='Ranking', ascending=False)
df3

CountryCode Ranking              Economy Millions of US Dollars  \
98          CIV      99        Côte d'Ivoire                24,680    
97          CMR      98             Cameroon                25,322    
96          PRY      97             Paraguay                25,502    
95          BOL      96              Bolivia                27,035    
94          TZA      95             Tanzania                28,242    
..          ...     ...                  ...                    ...   
101         CYP     102               Cyprus                22,767    
100         TTO     101  Trinidad and Tobago                23,320    
99          SLV     100          El Salvador                23,864    
9           IND      10                India             1,841,710    
0           USA       1        United States            16,244,600    

                           Long Name          Income Group  \
98         Republic of Côte d'Ivoire   Lower middle income   
97              Republic of Cameroon   Lower middle income   
96              Republic of Paraguay   Lower middle income   
95    Plurinational State of Bolivia   Lower middle income   
94       United Republic of Tanzania            Low income   
..                               ...                   ...   
101               Republic of Cyprus  High income: nonOECD   
100  Republic of Trinidad and Tobago  High income: nonOECD   
99           Republic of El Salvador   Lower middle income   
9                  Republic of India   Lower middle income   
0           United States of America     High income: OECD   

                        Region Lending category Other groups  \
98          Sub-Saharan Africa              IDA         HIPC   
97          Sub-Saharan Africa              IDA         HIPC   
96   Latin America & Caribbean             IBRD          NaN   
95   Latin America & Caribbean            Blend         HIPC   
94          Sub-Saharan Africa              IDA         HIPC   
..                         ...              ...          ...   
101      Europe & Central Asia              NaN    Euro area   
100  Latin America & Caribbean             IBRD          NaN   
99   Latin America & Caribbean             IBRD          NaN   
9                   South Asia            Blend          NaN   
0                North America              NaN          NaN   

                  Currency Unit  ...  \
98                    CFA franc  ...   
97                    CFA franc  ...   
96           Paraguayan guarani  ...   
95           Bolivian Boliviano  ...   
94           Tanzanian shilling  ...   
..                          ...  ...   
101                        Euro  ...   
100  Trinidad and Tobago dollar  ...   
99                  U.S. dollar  ...   
9                  Indian rupee  ...   
0                   U.S. dollar  ...   

    Source of most recent Income and expenditure data  \
98                                          IHS, 2002   
97                                           PS, 2001   
96                                          IHS, 2007   
95                                          IHS, 2007   
94                                     ES/BS, 2000/01   
..                                                ...   
101                                               NaN   
100                                         IHS, 1992   
99                                          IHS, 2007   
9                                        IHS, 2004/05   
0                                            LFS 2000   

    Vital registration complete Latest agricultural census  \
98                          NaN                       2001   
97                          NaN                       1984   
96                          NaN                       1991   
95                          NaN                  1984-1988   
94                          NaN                  2002-2003   
..                          ...                        ...   
101                         Yes      

In [45]:
#The 13th country by GDP is Spain
df3[df3['Ranking']=='13']

CountryCode Ranking Economy Millions of US Dollars         Long Name  \
12         ESP      13   Spain             1,322,965   Kingdom of Spain   

         Income Group                 Region Lending category Other groups  \
12  High income: OECD  Europe & Central Asia              NaN    Euro area   

   Currency Unit  ... Source of most recent Income and expenditure data  \
12          Euro  ...                                         IHS, 2000   

   Vital registration complete Latest agricultural census  \
12                         Yes                       1999   

   Latest industrial data  Latest trade data  Latest water withdrawal data  \
12                 2004.0             2008.0                        2000.0   

   2-alpha code WB-2 code  Table Name Short Name  
12           ES        ES       Spain      Spain  

[1 rows x 34 columns]

- d. What is the average GDP for the "High income: OECD" and "High income: nonOECD" group? [6 pts]

In [46]:
### Code Starts Here
oecd = df3[df3['Income Group'] == 'High income: OECD']
oecd

CountryCode Ranking          Economy Millions of US Dollars  \
8           ITA       9            Italy             2,014,670    
79          SVN      80         Slovenia                45,279    
73          LUX      74       Luxembourg                55,178    
62          SVK      63  Slovak Republic                91,149    
5           GBR       6   United Kingdom             2,471,784    
57          HUN      58          Hungary               124,600    
54          NZL      55      New Zealand               167,347    
50          CZE      51   Czech Republic               196,446    
4           FRA       5           France             2,612,878    
45          IRL      46          Ireland               210,771    
44          PRT      45         Portugal               212,274    
42          FIN      43          Finland               247,546    
41          GRC      42           Greece               249,099    
39          ISR      40           Israel               258,217    
3           DEU       4          Germany             3,428,131    
32          DNK      33          Denmark               314,887    
2           JPN       3            Japan             5,959,718    
26          AUT      27          Austria               394,708    
24          BEL      25          Belgium               483,262    
23          POL      24           Poland               489,795    
22          NOR      23           Norway               499,667    
20          SWE      21           Sweden               523,806    
19          CHE      20      Switzerland               631,173    
17          NLD      18      Netherlands               770,555    
14          KOR      15      Korea, Rep.             1,129,598    
12          ESP      13            Spain             1,322,965    
121         ISL     122          Iceland                13,579    
11          AUS      12        Australia             1,532,408    
10          CAN      11           Canada             1,821,424    
0           USA       1    United States            16,244,600    

                                             Long Name       Income Group  \
8                                     Italian Republic  High income: OECD   
79                                Republic of Slovenia  High income: OECD   
73                           Grand Duchy of Luxembourg  High income: OECD   
62                                     Slovak Republic  High income: OECD   
5    United Kingdom of Great Britain and Northern I...  High income: OECD   
57                                 Republic of Hungary  High income: OECD   
54                                         New Zealand  High income: OECD   
50                                      Czech Republic  High income: OECD   
4                                      French Republic  High income: OECD   
45                                             Ireland  High income: OECD   
44                                 Portuguese Republic  High income: OECD   
42                                 Republic of Finland  High income: OECD   
41                                   Hellenic Republic  High income: OECD   
39                                     State of Israel  High income: OECD   
3                          Federal Republic of Germany  High income: OECD   
32                                  Kingdom of Denmark  High income: OECD   
2                                                Japan  High income: OECD   
26                                 Republic of Austria  High income: OECD   
24                                  Kingdom of Belgium  High income: OECD   
23                                  Republic of Poland  High income: OECD   
22                                   Kingdom of Norway  High income: OECD   
20                                   Kingdom of Sweden  High income: OECD   
19                                         Switzerland  High income: OECD   
17                          Kingdom of the Netherlands  High income: OECD   
1

In [47]:
#The GDP column contains strings with commas in it. We must remove the commas and conver the column type to int
oecd['Millions of US Dollars'] = oecd['Millions of US Dollars'].str.replace(',', '').astype(int)

<ipython-input-47-e1caf5f5b34f>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  oecd['Millions of US Dollars'] = oecd['Millions of US Dollars'].str.replace(',', '').astype(int)


In [48]:
#The average GDP for High income OECD group is 
oecd['Millions of US Dollars'].mean()

1483917.1333333333

In [49]:
#make new df with only non oecd
non_oecd = df3[df3['Income Group'] == 'High income: nonOECD']
non_oecd

CountryCode Ranking               Economy Millions of US Dollars  \
93          LVA      94                Latvia                28,373    
92          BHR      93               Bahrain                29,044    
81          MAC      82      Macao SAR, China                43,582    
70          HRV      71               Croatia                59,228    
65          OMN      66                  Oman                69,972    
60          PRI      61           Puerto Rico               101,496    
55          KWT      56                Kuwait               160,913    
53          QAT      54                 Qatar               171,476    
36          HKG      37  Hong Kong SAR, China               263,259    
34          SGP      35             Singapore               274,701    
31          ARE      32  United Arab Emirates               348,595    
18          SAU      19          Saudi Arabia               711,050    
159         ABW     161                 Aruba                 2,584    
151         BRB     153              Barbados                 4,225    
147         BMU     149               Bermuda                 5,474    
145         MCO     147                Monaco                 6,075    
136         BHS     138          Bahamas, The                 8,149    
135         MLT     137                 Malta                 8,722    
112         BRN     113     Brunei Darussalam                16,954    
109         GNQ     110     Equatorial Guinea                17,697    
102         EST     103               Estonia                22,390    
101         CYP     102                Cyprus                22,767    
100         TTO     101   Trinidad and Tobago                23,320    

                                             Long Name          Income Group  \
93                                  Republic of Latvia  High income: nonOECD   
92                                  Kingdom of Bahrain  High income: nonOECD   
81   Macao Special Administrative Region of the Peo...  High income: nonOECD   
70                                 Republic of Croatia  High income: nonOECD   
65                                   Sultanate of Oman  High income: nonOECD   
60                                         Puerto Rico  High income: nonOECD   
55                                     State of Kuwait  High income: nonOECD   
53                                      State of Qatar  High income: nonOECD   
36   Hong Kong Special Administrative Region of the...  High income: nonOECD   
34                               Republic of Singapore  High income: nonOECD   
31                                United Arab Emirates  High income: nonOECD   
18                             Kingdom of Saudi Arabia  High income: nonOECD   
159                                              Aruba  High income: nonOECD   
151                                           Barbados  High income: nonOECD   
147                                       The Bermudas  High income: nonOECD   
145                             Principality of Monaco  High income: nonOECD   
136                        Commonwealth of The Bahamas  High income: nonOECD   
135                                  Republic of Malta  High income: nonOECD   
112                                  Brunei Darussalam  High income: nonOECD   
109                      Republic of Equatorial Guinea  High income: nonOECD   
102                                Republic of Estonia  High income: nonOECD   
101                                 Republic of Cyprus  High income: nonOECD   
100                    Republic of Trinidad and Tobago  High income: nonOECD   

                         Region Lending category Other groups  \
93        Europe & Central Asia              NaN          NaN   
92   Middle East & North Africa              NaN          NaN   
81          East Asia & Pacific              NaN          NaN   
70        Europe & Central Asia             IBRD          NaN   
65   Middle East & North Afri

In [50]:
#format GDP column
non_oecd['Millions of US Dollars'] = non_oecd['Millions of US Dollars'].str.replace(',', '').astype(int)

<ipython-input-50-b93a6d299ae8>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_oecd['Millions of US Dollars'] = non_oecd['Millions of US Dollars'].str.replace(',', '').astype(int)


In [51]:
#The average gdp for non oecd is
non_oecd['Millions of US Dollars'].mean()

104349.82608695653

- e. What is the average GDP for different income groups and regions? [6 pts]

In [53]:
#format Millions of US Dollars in df3
df3['Millions of US Dollars'] = df3['Millions of US Dollars'].str.replace(',', '').astype(int)

In [54]:
#Group by income and region and take the average for millions of us dollars
incomeRegion = df3.groupby(['Income Group','Region'])['Millions of US Dollars'].mean()
incomeRegion

Income Group          Region                    
High income: OECD     East Asia & Pacific           2.197268e+06
                      Europe & Central Asia         7.567044e+05
                      Middle East & North Africa    2.582170e+05
                      North America                 9.033012e+06
High income: nonOECD  East Asia & Pacific           1.496240e+05
                      Europe & Central Asia         2.776660e+04
                      Latin America & Caribbean     2.795480e+04
                      Middle East & North Africa    2.142531e+05
                      North America                 5.474000e+03
                      Sub-Saharan Africa            1.769700e+04
Low income            East Asia & Pacific           8.154667e+03
                      Europe & Central Asia         6.723500e+03
                      Latin America & Caribbean     7.843000e+03
                      South Asia                    5.193833e+04
                      Sub-Saharan Africa 